import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Fuentes (opcional)
// Font.register({ family: 'Inter', src: '...' });

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#0a0a0a',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2pt solid #00E5FF',
    paddingBottom: 15,
  },
  title: {
    fontSize: 28,
    color: '#00E5FF',
    fontWeight: 'bold',
  },
  subtitle: {
    fontSize: 14,
    color: '#F0C05A', // Gold
    marginTop: 8,
  },
  section: {
    margin: 10,
    padding: 10,
  },
  content: {
    fontSize: 12,
    lineHeight: 1.6,
    color: '#E0E0E0',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#F0C05A',
    fontSize: 10,
    borderTop: '1pt solid #333333',
    paddingTop: 10,
  }
});

interface ProposalPDFProps {
  companyName: string;
  content: string; // Markdown content from Gemini
}

export const ProposalPDF = ({ companyName, content }: ProposalPDFProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Propuesta de Estrategia Digital</Text>
        <Text style={styles.subtitle}>Preparado exclusivamente para: {companyName}</Text>
      </View>
      
      <View style={styles.section}>
        <Text style={styles.content}>
          {/* react-pdf doesn't support Markdown natively, so we render raw text or need a markdown parser.
              For V1, we just render the raw text generated by Gemini. */}
          {content}
        </Text>
      </View>

      <Text style={styles.footer}>
        ADNQN Intelligence Platform - Generado Automáticamente por IA
      </Text>
    </Page>
  </Document>
);
